
package view;

import model.Controler;
import model.HocVien;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;


/**
 *
 * @author PH Laptop
 */
public class HomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    private HocVien[] arr = Controler.readFromFile("hocvien.txt");
    private DefaultTableModel model;
    private DefaultTableModel table_update;
    private DefaultTableModel statistical;
   
    
    public HomeJFrame() {
        initComponents();
        setTitle("Quản lý điểm");
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) List.getModel();
        table_update = (DefaultTableModel) Update.getModel();
        statistical = (DefaultTableModel) Table_statistical.getModel();
        this.ShowList(arr,model);
        this.ShowList(arr,table_update);
        this.Statistical();
    }
    public void ShowList(HocVien[] hv,DefaultTableModel table){
        table.setRowCount(0);
        for(int i=0;i<hv.length;i++)
            this.ShowData(hv[i],table);
    }
    public void Statistical(){
       statistical.setRowCount(0);
       for(int i=0;i<arr.length;i++)
           if(arr[i].getDiemthi()<4)
               this.ShowData(arr[i],statistical);
    }
    public void ShowData(HocVien hv,DefaultTableModel table){
//        table_update.setRowCount(0);
        table.addRow(new Object[] {
            hv.getMahv(),hv.getHovaten(),hv.getDiemthi(),hv.getMon(),hv.getLop()
        });
                
            
    }
   
    public int check(String ma){
        int k = -1 ;
        for(int i=0;i<arr.length;i++)
            if(arr[i].getMahv().equals(ma)){
                k = i ;
                break ;
            }
        return k ;
    }
    public void addHocVien(HocVien h){
        if(check(h.getMahv())!=-1){
            JOptionPane.showMessageDialog(rootPane,"Mã hoc viên này đã tồn tại");
            return ;
        }
        arr = Controler.Add(arr, h);
        this.ShowList(arr,model);
        this.ShowList(arr,table_update);
        this.Statistical();
        Controler.writeToFile("hocvien.txt", h);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenu3 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jFrame1 = new javax.swing.JFrame();
        jMenu1 = new javax.swing.JMenu();
        Tab1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        List = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Sort = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        Tab3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        MaHV = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Update = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        SuaDiem = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        Fin = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table_statistical = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        jToggleButton1.setText("jToggleButton1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("jMenu3");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tab1.setBackground(new java.awt.Color(204, 204, 204));
        Tab1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tab1.setToolTipText("");
        Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tab1.setPreferredSize(new java.awt.Dimension(749, 470));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setToolTipText("QUẢN LÝ ĐIỂM");

        List.setBackground(new java.awt.Color(0, 255, 255));
        List.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        List.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HV", "Họ và tên", "Điểm", "Môn", "Lớp"
            }
        ));
        List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(List);
        if (List.getColumnModel().getColumnCount() > 0) {
            List.getColumnModel().getColumn(0).setPreferredWidth(10);
            List.getColumnModel().getColumn(1).setPreferredWidth(50);
            List.getColumnModel().getColumn(2).setPreferredWidth(8);
            List.getColumnModel().getColumn(3).setPreferredWidth(20);
            List.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        Delete.setBackground(new java.awt.Color(255, 102, 102));
        Delete.setText("Xóa học viên");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Add.setBackground(new java.awt.Color(51, 255, 51));
        Add.setText("Thêm học viên");
        Add.setMaximumSize(new java.awt.Dimension(93, 23));
        Add.setMinimumSize(new java.awt.Dimension(93, 23));
        Add.setPreferredSize(new java.awt.Dimension(93, 23));
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(255, 0, 0));
        Exit.setText("Thoát");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không sắp xếp", "Sắp xếp điểm theo chiều tăng dần", "Sắp xếp điểm theo chiều giảm dần" }));
        Sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("XEM ĐIỂM");

        jButton5.setIcon(new javax.swing.ImageIcon("D:\\java\\Nhom6\\bt-java\\images\\save-file.png")); // NOI18N
        jButton5.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton5.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton5.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel13.setText("Nhập mã học viên");

        jButton8.setText("OK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Clean");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(288, 288, 288)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(Delete)
                                .addGap(94, 94, 94)
                                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(Sort, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton9))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        Tab1.addTab("Xem điểm", jPanel1);

        Tab3.setBackground(new java.awt.Color(153, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("NHẬP/SỬA ĐIỂM");

        MaHV.setBackground(new java.awt.Color(153, 255, 153));
        MaHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaHVActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Nhập mã học viên");

        Update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HV", "Họ và tên", "Điểm", "Môn", "Lớp"
            }
        ));
        Update.setRowHeight(15);
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Update);
        if (Update.getColumnModel().getColumnCount() > 0) {
            Update.getColumnModel().getColumn(0).setPreferredWidth(8);
            Update.getColumnModel().getColumn(2).setPreferredWidth(15);
            Update.getColumnModel().getColumn(3).setPreferredWidth(15);
            Update.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        jButton3.setText("Tìm kiếm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Clean");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        SuaDiem.setBackground(new java.awt.Color(153, 255, 153));
        SuaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaDiemActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Nhập điểm");

        jButton7.setText("Clean");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        Fin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Fin.setForeground(new java.awt.Color(0, 153, 0));

        jButton10.setBackground(new java.awt.Color(255, 153, 51));
        jButton10.setText("Nhập điểm");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 255, 0));
        jButton11.setText("Sửa điểm");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Tab3Layout = new javax.swing.GroupLayout(Tab3);
        Tab3.setLayout(Tab3Layout);
        Tab3Layout.setHorizontalGroup(
            Tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab3Layout.createSequentialGroup()
                .addGroup(Tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(Fin))
                    .addGroup(Tab3Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(Tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Tab3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(71, 71, 71)
                                .addGroup(Tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Tab3Layout.createSequentialGroup()
                                        .addComponent(jButton10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton11))
                                    .addComponent(SuaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tab3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(Tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(MaHV, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)))
                        .addGroup(Tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addComponent(jButton7)))
                    .addGroup(Tab3Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel10)))
                .addContainerGap(223, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        Tab3Layout.setVerticalGroup(
            Tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(24, 24, 24)
                .addGroup(Tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaHV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(13, 13, 13)
                .addGroup(Tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(SuaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(Tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Fin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Tab1.addTab("Nhập/Sửa điểm", Tab3);

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("DANH SÁCH HỌC VIÊN THI LẠI");

        Table_statistical.setBackground(new java.awt.Color(255, 255, 51));
        Table_statistical.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Table_statistical.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HV", "Họ và tên", "Điểm", "Môn", "Lớp"
            }
        ));
        jScrollPane4.setViewportView(Table_statistical);
        if (Table_statistical.getColumnModel().getColumnCount() > 0) {
            Table_statistical.getColumnModel().getColumn(0).setMinWidth(50);
            Table_statistical.getColumnModel().getColumn(0).setPreferredWidth(50);
            Table_statistical.getColumnModel().getColumn(0).setMaxWidth(50);
            Table_statistical.getColumnModel().getColumn(1).setMinWidth(200);
            Table_statistical.getColumnModel().getColumn(1).setPreferredWidth(200);
            Table_statistical.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        Tab1.addTab("Thống kê", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tab1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tab1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void SortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortActionPerformed

        int index = Sort.getSelectedIndex();
        if(index>=0){
            if(index==0){
                this.ShowList(arr,model);
            }
            else if(index==1){
                HocVien[] the = Gan();
                Controler.Sort(the,true);
                this.ShowList(the, model);
                this.ShowList(the,table_update);
            }
            else if(index==2){
                HocVien[] the = Gan();
                Controler.Sort(the,false);
                this.ShowList(the, model);
                this.ShowList(the,table_update);
            }
        }
    }//GEN-LAST:event_SortActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn lưu lại ko", "QUESTION", JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION){
            Controler.SaveData("hocvien.txt", arr);
        }
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if(Search.getText().trim().length()==0){
            JOptionPane.showMessageDialog(rootPane,"Vui lòng nhập vào mã học viên", "ERROR",JOptionPane.ERROR_MESSAGE);
            return ;
        }
        int index = check(Search.getText());
        if(index ==-1){
           JOptionPane.showMessageDialog(rootPane,"Mã học viên không tồn tại", "ERROR",JOptionPane.ERROR_MESSAGE);
           return ;
        }
        int n = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa học viên này không", "QUESTION", JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION){
            arr = Controler.Delete(arr, index);
            this.ShowList(arr,model);
            this.Statistical();
            this.ShowList(arr,table_update);
            Search.setText("");
        }   
    }//GEN-LAST:event_DeleteActionPerformed
    
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        new add(this, rootPaneCheckingEnabled).setVisible(true);
       
    }//GEN-LAST:event_AddActionPerformed
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        SuaDiem.setText("");
        Fin.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void SuaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaDiemActionPerformed

    }//GEN-LAST:event_SuaDiemActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MaHV.setText("");
        Fin.setText("");
        this.ShowList(arr, table_update);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String ma = MaHV.getText();
        if(ma.trim().length()==0)
            JOptionPane.showMessageDialog(rootPane,"Vui lòng nhập vào mã học viên","MESSAGE",JOptionPane.INFORMATION_MESSAGE);
        else if(check(ma)!=-1){    
            int index = check(ma) ;
            
            SuaDiem.setText(String.valueOf(arr[index].getDiemthi()));
            if(arr[index].getDiemthi()==-1)
                SuaDiem.setText("");
            table_update.setRowCount(0);
            this.ShowData(arr[index],table_update);      
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Mã học viên không tồn tại", "ERROL",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void MaHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaHVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaHVActionPerformed

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        
            int index = Update.getSelectedRow();
            if(index==-1)
                return ;
            else{
                String ma = (String) table_update.getValueAt(index, 0);
                MaHV.setText(ma);
                SuaDiem.setText(String.valueOf(arr[index].getDiemthi()));
                if(arr[index].getDiemthi()==-1){
                    SuaDiem.setText("");
                }
                    
                
            }
           
        
        
    }//GEN-LAST:event_UpdateMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Controler.SaveData("hocvien.txt", arr);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(Search.getText().trim().length()==0){
            JOptionPane.showMessageDialog(rootPane,"Vui lòng nhập vào mã học viên","MESSAGE",JOptionPane.INFORMATION_MESSAGE);  
        }
        else{
            String ma = Search.getText();
            if(check(ma)==-1){
               JOptionPane.showMessageDialog(rootPane,"Mã học viên không tồn tại","MESSAGE",JOptionPane.INFORMATION_MESSAGE);  
            }
            else{
                int i = check(ma);
                model.setRowCount(0);
                this.ShowData(arr[i], model);
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Search.setText("");
        this.ShowList(arr,model);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListMouseClicked
        int indexRow = List.getSelectedRow();
        Search.setText((String) List.getValueAt(indexRow, 0));
    }//GEN-LAST:event_ListMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        if(MaHV.getText().trim().length()==0){
            JOptionPane.showMessageDialog(rootPane,"Vui lòng nhập mã học viên", "ERROR",JOptionPane.ERROR_MESSAGE);
        
        }
        else{
            int index = check(MaHV.getText());
            if(SuaDiem.getText().length()==0 && index!=-1 ){
                JOptionPane.showMessageDialog(rootPane,"Vui lòng nhập điểm", "ERROR",JOptionPane.ERROR_MESSAGE);
            }
            if(index!=-1){
                if(arr[index].getDiemthi()!=-1){
                    JOptionPane.showMessageDialog(rootPane,"Điểm của sinh viên đã được nhập");
                    MaHV.setText("");
                    SuaDiem.setText("");
                    this.ShowList(arr, table_update);
                    return;
                }
                float Diem = Float.parseFloat(SuaDiem.getText());
                arr[index].setDiemthi(Diem);
                this.ShowList(arr, model);
                this.ShowList(arr, table_update);
                this.Statistical();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Mã học viên không tồn tại", "ERROL",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(MaHV.getText().trim().length()==0){
            JOptionPane.showMessageDialog(rootPane,"Vui lòng nhập mã học viên", "ERROR",JOptionPane.ERROR_MESSAGE);
        
        }
        else{
            int index = check(MaHV.getText());
            if(SuaDiem.getText().length()==0 && index!=-1 ){
                JOptionPane.showMessageDialog(rootPane,"Vui lòng nhập điểm", "ERROR",JOptionPane.ERROR_MESSAGE);
            }
            if(index!=-1){
                if(arr[index].getDiemthi()==-1){
                    JOptionPane.showMessageDialog(rootPane,"Điểm của sinh viên chưa được nhập");
                    MaHV.setText("");
                    SuaDiem.setText("");
                    this.ShowList(arr, table_update);
                    return;
                }
                float Diem = Float.parseFloat(SuaDiem.getText());
                arr[index].setDiemthi(Diem);
                this.ShowList(arr, model);
                this.ShowList(arr, table_update);
                this.Statistical();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Mã học viên không tồn tại", "ERROL",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed
           
    public HocVien[] Gan(){
        HocVien[] temp = new HocVien[arr.length];
        for(int i=0;i<this.arr.length;i++){
            temp[i] = arr[i];
        }
        return temp;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
               
            }
        });
    }
    private javax.swing.JTextField InputDiem;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Fin;
    private javax.swing.JTable List;
    private javax.swing.JTextField MaHV;
    private javax.swing.JTextField Search;
    private javax.swing.JComboBox<String> Sort;
    private javax.swing.JTextField SuaDiem;
    private javax.swing.JTabbedPane Tab1;
    private javax.swing.JPanel Tab3;
    private javax.swing.JTable Table_statistical;
    private javax.swing.JTable Update;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
